// SPDX-FileCopyrightText: 2026 Tech Valley Center of Gravity
// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Adds a "Generate" control to the door-sync webhook secret field on
 * Administer > System Settings > Door-Sync CiviRules Webhook Settings.
 *
 * The page itself is generated by CRM_Admin_Form_Generic from setting
 * metadata, so there is no form class to hang a button on; doorsync.php loads
 * this file from hook_civicrm_buildForm instead.
 *
 * The value is generated in the browser and only reaches the database when the
 * form is saved, which keeps Cancel meaning what it says.
 */
CRM.$(function ($) {
  'use strict';

  var $field = $('input[name="doorsync_webhook_secret"]');
  if (!$field.length) {
    // The generated form changed shape. Leave the page exactly as it was.
    return;
  }

  // No CSPRNG, no button. Math.random() is not an acceptable fallback for a
  // shared secret, and a weak secret that looks fine is worse than no control.
  if (!window.crypto || typeof window.crypto.getRandomValues !== 'function') {
    return;
  }

  /**
   * 32 bytes as lowercase hex — the same shape as `openssl rand -hex 32`.
   * HMAC-SHA256 gains nothing from a key longer than its 32-byte block output.
   *
   * @returns {string}
   */
  function generateSecret() {
    var bytes = new Uint8Array(32);
    window.crypto.getRandomValues(bytes);
    return Array.prototype.map.call(bytes, function (b) {
      return ('0' + b.toString(16)).slice(-2);
    }).join('');
  }

  var $button = $('<button/>', {
    // Explicitly not a submit button: this sits inside a QuickForm.
    type: 'button',
    'class': 'crm-button',
    text: ts('Generate')
  });

  var $hint = $('<div/>', {
    'class': 'description',
    css: { marginTop: '0.5em' }
  }).hide();

  $field.after($hint).after(' ').after($button);

  $button.on('click', function () {
    // Reveal it: the whole point of generating a secret here is to copy it to
    // the Worker, and it is masked again as soon as the page reloads.
    $field.val(generateSecret()).attr('type', 'text').trigger('change');
    $hint
      .text(ts('Copy this value to the Worker (CIVICRM_WEBHOOK_SECRET), then save. The Worker rejects every webhook until both sides match.'))
      .show();
  });
});
